### ISSUE TITLE
PhiloGL does not appear to work on two canvases at the same time

### ISSUE THREAD

**Issue by philogb** [philogb/philogl#16]
- Create a test example with two canvases and philogl using both of them.
 - The `app` object seems to be kept in state in across the code, modularize so that `app` is pulled out.

**Comment by ibgreen** [comment]
@wwwtyro I think you worked on this. Is there an example that shows this working? If so we can close.

**Comment by wwwtyro** [comment]
Yes, but it was a silly example for testing it out. I'll make a better one right now. :)

**Comment by wwwtyro** [comment]
https://github.com/philogb/philogl/pull/46
