### ISSUE TITLE
Move codebase to use browserify

### ISSUE THREAD

**Issue by philogb** [philogb/philogl#17]
We'd like to change the codebase to be using browserify

**Comment by ibgreen** [comment]
Thanks to @wwwtyro's support, this is now working on ES6 branch, and browserify based applications should be able to consume (e.g. build and source debug) the module by adding a github link in package.json (we haven't published to npm). 

For practical reasons (to avoid dozens of build targets) the examples are still "script based", they now include the basic philogl library bundle (built by browserify) using an HTML script statement.
